name: Проверка задания

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true

  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    needs: lint  # Запускать тесты после завершения линтинга
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest tests --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit/test-results.xml"
        if: always()
